### ISSUE TITLE
 negative sizes are not supported in the flow layout after updating 0.4.5 in month view

### ISSUE THREAD

**Issue by learnasucan** [kvyatkovskys/KVKCalendar#139]
**Describe the bug**
 Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'negative sizes are not supported in the flow layout'

**To Reproduce**
1.Update 0.4.5 from feature or master branch
2. Go to monthView
3. your screen gets stuck
4. No scroll down
5. See error

**Expected behavior**
Month view should not stuck and not crashed nor freezed

**Additional context**

**Comment by kvyatkovskys** [comment]
The issue is already fixed in `feature/v_0.4.6`. Thx for the report 🙂

**Comment by learnasucan** [comment]
> The issue is already fixed in `feature/v_0.4.6`. Thx for the report 🙂
Is it correct way to use this?
 ` pod 'KVKCalendar' , :git => 'https://github.com/kvyatkovskys/KVKCalendar/tree/feature/v_0.4.6', :branch => 'feature/v_0.4.6' `

**Comment by learnasucan** [comment]
> > The issue is already fixed in `feature/v_0.4.6`. Thx for the report 🙂
> > Is it correct way to use this?
> > `pod 'KVKCalendar' , :git => 'https://github.com/kvyatkovskys/KVKCalendar/tree/feature/v_0.4.6', :branch => 'feature/v_0.4.6'`

I have tried using this 
`pod 'KVKCalendar' , :git => 'https://github.com/kvyatkovskys/KVKCalendar.git', :branch => 'feature/v_0.4.6'`
but same issue persist.
can you update the version?

**Comment by kvyatkovskys** [comment]
I'm still working on this branch.

**Comment by UmeshCW** [comment]
@kvyatkovskys any updates on this? I am also facing same issue.

**Comment by kvyatkovskys** [comment]
The next version will release on this weekend.

**Comment by prachit1105** [comment]
> The next version will release on this weekend.
Really appreciated ..
